"""Grouped q3-free planning and exact summation entry points.

The hot implementation stays in ``engine.py`` so the reduction core remains
contiguous. This module provides a domain-scoped import surface without
changing the reducer's runtime path.
"""

from __future__ import annotations

from .engine import (
    Q3FreeBranchTemplate,
    _Q3FreeConstraintComponentPlan,
    _Q3FreeConstraintPlan,
    _Q3FreeCutsetCandidateEvaluation,
    _Q3FreeCutsetConditioningPlan,
    _Q3FreeRawConstraintPlan,
    _Q3FreeRawConstraintRestrictedPlan,
    _build_native_q3_free_treewidth_plan,
    _build_q3_free_branch_template,
    _build_q3_free_constraint_plan,
    _build_q3_free_cutset_residue_data,
    _build_q3_free_raw_constraint_plan,
    _classify,
    _elim_two_partner_constraint_q3_free,
    _evaluate_q3_free_branch_template_batch,
    _gauss_sum_q3_free,
    _gauss_sum_q3_free_scaled,
    _q3_free_cutset_conditioning_plan,
    _q3_free_edge_density,
    _q3_free_graph,
    _q3_free_one_shot_cutset_conditioning_plan,
    _q3_free_phase3_backend_name,
    _q3_free_prefers_locality_preserving_cutset,
    _q3_free_prefers_one_shot_cutset,
    _q3_free_prefers_reusable_cutset,
    _q3_free_treewidth_order,
    _sum_q3_free_component,
    _sum_q3_free_component_scaled,
    _sum_q3_free_treewidth_dp_scaled_batch,
    _sum_q3_free_via_bad_q2_cover_scaled,
    _sum_q3_free_via_cutset_conditioning_scaled,
    _sum_q3_free_via_gauss_reduction,
    _sum_q3_free_via_gauss_reduction_scaled,
    _sum_q3_free_via_nonquadratic_support,
    _sum_q3_free_via_nonquadratic_support_scaled,
)

__all__ = [
    "Q3FreeBranchTemplate",
    "_Q3FreeConstraintComponentPlan",
    "_Q3FreeConstraintPlan",
    "_Q3FreeCutsetCandidateEvaluation",
    "_Q3FreeCutsetConditioningPlan",
    "_Q3FreeRawConstraintPlan",
    "_Q3FreeRawConstraintRestrictedPlan",
    "_build_native_q3_free_treewidth_plan",
    "_build_q3_free_branch_template",
    "_build_q3_free_constraint_plan",
    "_build_q3_free_cutset_residue_data",
    "_build_q3_free_raw_constraint_plan",
    "_classify",
    "_elim_two_partner_constraint_q3_free",
    "_evaluate_q3_free_branch_template_batch",
    "_gauss_sum_q3_free",
    "_gauss_sum_q3_free_scaled",
    "_q3_free_cutset_conditioning_plan",
    "_q3_free_edge_density",
    "_q3_free_graph",
    "_q3_free_one_shot_cutset_conditioning_plan",
    "_q3_free_phase3_backend_name",
    "_q3_free_prefers_locality_preserving_cutset",
    "_q3_free_prefers_one_shot_cutset",
    "_q3_free_prefers_reusable_cutset",
    "_q3_free_treewidth_order",
    "_sum_q3_free_component",
    "_sum_q3_free_component_scaled",
    "_sum_q3_free_treewidth_dp_scaled_batch",
    "_sum_q3_free_via_bad_q2_cover_scaled",
    "_sum_q3_free_via_cutset_conditioning_scaled",
    "_sum_q3_free_via_gauss_reduction",
    "_sum_q3_free_via_gauss_reduction_scaled",
    "_sum_q3_free_via_nonquadratic_support",
    "_sum_q3_free_via_nonquadratic_support_scaled",
]
